services:
  nginx:
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    container_name: "mstroy-test-${ENV:-dev}"
    restart: unless-stopped
    environment:
      - NGINX_PORT=80
    networks:
      - default

networks:
  default:
    name: mstroy-test-${ENV:-dev}
