services:
  frontend:
    image: node:22-alpine
    working_dir: "/app"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: "sh -c 'npm install && npm run dev'"
    env_file:
      - .env
  nginx:
    environment:
      - NGINX_PORT=80
    user: root
    ports:
      - "8080:80"

volumes:
  node_modules:
